import { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { ArrowLeft, Sparkles, Loader2, AlertCircle, Clock, User } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { motion } from 'framer-motion';
import ReactMarkdown from 'react-markdown';
import { supabase } from '@/integrations/supabase/client';
import { format } from 'date-fns';

export default function SharedThemeAnalysis() {
  const { shareId } = useParams<{ shareId: string }>();
  const navigate = useNavigate();
  const [analysis, setAnalysis] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!shareId) return;
    loadAnalysis();
  }, [shareId]);

  const loadAnalysis = async () => {
    try {
      const { data, error: err } = await supabase
        .from('saved_theme_analyses')
        .select('*')
        .eq('share_id', shareId)
        .eq('is_public', true)
        .maybeSingle();

      if (err) throw err;
      if (!data) {
        setError('Analysis not found or is private.');
        return;
      }
      setAnalysis(data);
    } catch (e: any) {
      setError(e.message || 'Failed to load analysis');
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    );
  }

  if (error || !analysis) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="text-center space-y-4">
          <AlertCircle className="h-12 w-12 text-muted-foreground mx-auto" />
          <p className="text-muted-foreground">{error || 'Analysis not found.'}</p>
          <Button variant="outline" onClick={() => navigate('/')}>
            <ArrowLeft className="h-4 w-4 mr-2" /> Back to Home
          </Button>
        </div>
      </div>
    );
  }

  const themeData = analysis.theme_data as any;
  const tickers = themeData?.tickers || [];

  return (
    <div className="min-h-screen bg-background">
      <div className="border-b border-border/40 bg-card/30 backdrop-blur-sm sticky top-0 z-30">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 py-3 sm:py-4 flex items-center gap-3">
          <Button variant="ghost" size="sm" onClick={() => navigate('/')} className="shrink-0">
            <ArrowLeft className="h-4 w-4" />
          </Button>
          <div className="min-w-0">
            <h1 className="text-sm sm:text-base font-mono font-bold text-foreground truncate">
              {analysis.title}
            </h1>
            <div className="flex items-center gap-2 text-[10px] sm:text-xs text-muted-foreground font-mono">
              <span>Shared Analysis</span>
              {analysis.category && <span>• {analysis.category}</span>}
              <span className="flex items-center gap-1">
                <Clock className="h-3 w-3" />
                {format(new Date(analysis.created_at), 'MMM d, yyyy')}
              </span>
            </div>
          </div>
        </div>
      </div>

      <motion.div
        initial={{ opacity: 0, y: 12 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.4 }}
        className="max-w-4xl mx-auto px-4 sm:px-6 py-6 sm:py-10"
      >
        {tickers.length > 0 && (
          <div className="flex flex-wrap gap-2 mb-6">
            {tickers.slice(0, 8).map((t: any) => (
              <span
                key={t.symbol}
                className="px-2.5 py-1 rounded-full text-xs font-mono bg-card border border-border/60"
              >
                {t.symbol}{' '}
                <span className={t.change >= 0 ? 'text-emerald-400' : 'text-red-400'}>
                  {t.change >= 0 ? '+' : ''}{t.change?.toFixed(1)}%
                </span>
              </span>
            ))}
          </div>
        )}

        <div className="flex items-center gap-2 mb-6 px-3 py-2 rounded-lg bg-primary/5 border border-primary/20 w-fit">
          <Sparkles className="h-3.5 w-3.5 text-primary" />
          <span className="text-xs font-mono text-primary">
            Generated by AI • Shared analysis
          </span>
        </div>

        <div className="prose prose-invert prose-sm sm:prose-base max-w-none">
          <ReactMarkdown
            components={{
              h2: ({ children }) => (
                <h2 className="text-lg sm:text-xl font-mono font-bold text-foreground mt-8 mb-3 border-b border-border/30 pb-2">{children}</h2>
              ),
              h3: ({ children }) => (
                <h3 className="text-base sm:text-lg font-mono font-semibold text-foreground mt-6 mb-2">{children}</h3>
              ),
              p: ({ children }) => (
                <p className="text-sm sm:text-base text-foreground/80 leading-relaxed mb-3">{children}</p>
              ),
              ul: ({ children }) => (
                <ul className="space-y-1.5 mb-4 text-sm sm:text-base text-foreground/80">{children}</ul>
              ),
              li: ({ children }) => (
                <li className="flex gap-2">
                  <span className="text-primary mt-1.5 shrink-0">•</span>
                  <span>{children}</span>
                </li>
              ),
              strong: ({ children }) => (
                <strong className="text-foreground font-semibold">{children}</strong>
              ),
            }}
          >
            {analysis.analysis_content}
          </ReactMarkdown>
        </div>
      </motion.div>
    </div>
  );
}
